name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.0'

jobs:
  release:
    name: Release to Maven Central
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Install Redis CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y redis-tools
        
    - name: Start FalkorDB
      run: |
        docker run -d --name falkordb -p 6379:6379 falkordb/falkordb:latest
        # Wait for FalkorDB to be ready
        echo "Waiting for FalkorDB to start..."
        timeout 60 bash -c 'until nc -z localhost 6379; do sleep 1; done'
        echo "FalkorDB is ready"
        
    - name: Run full test suite
      run: ./mvnw clean verify -B -Dcheckstyle.skip=true
      env:
        MAVEN_OPTS: -Xmx1024m
        
    - name: Build and Package
      run: ./mvnw clean package -DskipTests -B -P release
      
    - name: Upload Release Assets
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/spring-data-falkordb-*.jar
        asset_name: spring-data-falkordb-${{ github.event.release.tag_name }}.jar
        asset_content_type: application/java-archive